[package]
name = "stocker"
version = "0.1.2"
authors = ["Teoh Han Hui <teohhanhui@gmail.com>"]
edition = "2018"
description = "Stocks dashboard"
readme = "README.md"
repository = "https://github.com/teohhanhui/stocker"
license = "MIT OR Apache-2.0"
keywords = ["finance", "stocks", "dashboard"]
categories = ["command-line-utilities", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.3"
better-panic = "0.2.0"
chrono = "0.4.11"
crossterm = "0.17.5"
err-derive = "0.2.4"
im = "15.0.0"
itertools = "0.9.0"
itertools-num = "0.1.3"
libmath = "0.2.1"
parking_lot = "0.10.2"
strum = "0.18.0"
strum_macros = "0.18.0"
tokio = "0.2.21"
tui = { version = "0.9.5", default-features = false, features = ['crossterm'] }
yahoo-finance = "0.3.0"

[patch.crates-io]
tui = { git = "https://github.com/fdehau/tui-rs" }
yahoo-finance = { git = "https://github.com/fbriden/yahoo-finance-rs" }
